/* The following code was generated by JFlex 1.4.3 on 09/11/22 05:01 */

package compiladoresproyecto;
import static compiladoresproyecto.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 09/11/22 05:01 from the specification file
 * <tt>C:/Users/eljug/OneDrive/Documentos/NetBeansProjects/compiladoresProyecto/src/compiladoresproyecto/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\11\2\0\1\5\22\0\1\5\1\47\1\6\2\0"+
    "\1\45\1\52\1\0\1\55\1\56\1\10\1\46\1\54\1\4\1\12"+
    "\1\7\12\2\1\53\1\53\1\50\1\44\1\50\2\0\1\62\2\1"+
    "\1\1\1\1\1\64\5\1\1\1\1\1\1\60\1\1\1\61\2\1"+
    "\1\42\1\1\1\57\1\1\1\63\3\1\1\53\1\0\1\53\1\51"+
    "\1\1\1\0\1\13\1\14\1\20\1\32\1\21\1\33\1\37\1\27"+
    "\1\30\1\1\1\25\1\23\1\34\1\24\1\22\1\36\1\1\1\17"+
    "\1\15\1\16\1\31\1\40\1\41\1\35\1\26\1\43\1\53\1\3"+
    "\1\53\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\1"+
    "\2\4\1\6\20\2\1\7\2\4\1\10\1\11\1\10"+
    "\1\1\2\6\1\2\1\12\1\7\1\0\1\13\1\0"+
    "\2\6\1\7\30\2\1\14\2\2\1\14\12\2\1\11"+
    "\1\0\1\2\4\5\27\2\1\14\16\2\1\0\32\2"+
    "\1\3\7\2\1\14\7\2\1\14\2\2\1\14\1\2"+
    "\1\0\13\2\1\0\7\2\2\0\3\2\2\0\2\2"+
    "\5\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\u0173"+
    "\0\u01a8\0\u01dd\0\65\0\u0212\0\u0247\0\u027c\0\u02b1\0\u02e6"+
    "\0\u031b\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e"+
    "\0\u04c3\0\u04f8\0\u052d\0\u0562\0\u0597\0\u05cc\0\u0562\0\u0562"+
    "\0\65\0\u0601\0\u013e\0\u0636\0\u066b\0\65\0\65\0\u0173"+
    "\0\65\0\u06a0\0\u06d5\0\u06a0\0\u06a0\0\u070a\0\u073f\0\u0774"+
    "\0\u07a9\0\u07de\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c"+
    "\0\u0951\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4"+
    "\0\u0af9\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd\0\152\0\u0c02\0\u0c37"+
    "\0\u0c6c\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf"+
    "\0\u0e14\0\u0e49\0\u0e7e\0\65\0\u0eb3\0\u0ee8\0\65\0\u06a0"+
    "\0\u06d5\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u1026\0\u105b"+
    "\0\u1090\0\u10c5\0\u10fa\0\u112f\0\u1164\0\u1199\0\u11ce\0\u1203"+
    "\0\u1238\0\u126d\0\u12a2\0\u12d7\0\u130c\0\u1341\0\u1376\0\u13ab"+
    "\0\u13e0\0\u1415\0\u144a\0\u147f\0\u14b4\0\u14e9\0\u151e\0\u1553"+
    "\0\u1588\0\u15bd\0\u15f2\0\u1627\0\u165c\0\u1691\0\u16c6\0\u16fb"+
    "\0\u1730\0\u1765\0\u179a\0\u17cf\0\u1804\0\u1839\0\u186e\0\u18a3"+
    "\0\u18d8\0\u190d\0\u1942\0\u1977\0\u19ac\0\u19e1\0\u1a16\0\u1a4b"+
    "\0\u1a80\0\u1ab5\0\u1aea\0\u1b1f\0\u1b54\0\u1b89\0\u1bbe\0\u1bf3"+
    "\0\u1c28\0\u1c5d\0\u1c92\0\65\0\u1cc7\0\u1cfc\0\u1d31\0\u1d66"+
    "\0\u1d9b\0\u1dd0\0\u1e05\0\u1203\0\u1e3a\0\u1e6f\0\u1ea4\0\u1ed9"+
    "\0\u1f0e\0\u1f43\0\u1f78\0\u1fad\0\u1fe2\0\u2017\0\u204c\0\u2081"+
    "\0\u20b6\0\u20eb\0\u2120\0\u2155\0\u218a\0\u21bf\0\u21f4\0\u2229"+
    "\0\u225e\0\u2293\0\u22c8\0\u22fd\0\u2332\0\u2367\0\u239c\0\u23d1"+
    "\0\u2406\0\u243b\0\u2470\0\u24a5\0\u24da\0\u250f\0\u2544\0\u2579"+
    "\0\u25ae\0\u25e3\0\u2618\0\u264d\0\u2682\0\u26b7\0\u26ec\0\u2721"+
    "\0\u2756\0\u278b";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\7\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\3\1\23\1\24\3\3\1\25\1\3"+
    "\1\26\1\27\2\3\1\30\1\3\1\31\1\32\1\33"+
    "\1\3\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\13\1\43\1\44\1\13\1\45\5\3\66\0\2\3"+
    "\10\0\31\3\13\0\6\3\2\0\1\4\65\0\1\41"+
    "\65\0\1\46\37\0\1\47\25\0\1\7\3\0\1\7"+
    "\42\0\1\7\10\0\6\50\1\51\56\50\7\52\1\53"+
    "\1\54\1\0\32\52\1\55\27\52\1\54\1\52\1\0"+
    "\32\52\1\55\20\52\1\0\2\3\10\0\1\3\1\56"+
    "\1\57\26\3\13\0\6\3\1\0\2\3\10\0\4\3"+
    "\1\60\2\3\1\61\3\3\1\62\15\3\13\0\6\3"+
    "\1\0\2\3\10\0\3\3\1\63\7\3\1\64\1\65"+
    "\1\3\1\66\7\3\1\67\2\3\13\0\6\3\1\0"+
    "\2\3\10\0\4\3\1\70\7\3\1\71\14\3\13\0"+
    "\6\3\1\0\2\3\10\0\6\3\1\72\22\3\13\0"+
    "\6\3\1\0\2\3\10\0\1\73\6\3\1\74\1\75"+
    "\3\3\1\76\14\3\13\0\6\3\1\0\2\3\10\0"+
    "\10\3\1\77\1\100\10\3\1\101\6\3\13\0\6\3"+
    "\1\0\2\3\10\0\7\3\1\102\21\3\13\0\6\3"+
    "\1\0\2\3\10\0\1\103\5\3\1\104\22\3\13\0"+
    "\6\3\1\0\2\3\10\0\11\3\1\105\6\3\1\106"+
    "\1\107\7\3\13\0\6\3\1\0\2\3\10\0\6\3"+
    "\1\110\1\111\21\3\13\0\6\3\1\0\2\3\10\0"+
    "\7\3\1\112\1\113\4\3\1\114\13\3\13\0\6\3"+
    "\1\0\2\3\10\0\1\115\3\3\1\116\11\3\1\117"+
    "\12\3\13\0\6\3\1\0\2\3\10\0\7\3\1\120"+
    "\21\3\13\0\6\3\1\0\2\3\10\0\14\3\1\121"+
    "\14\3\13\0\6\3\1\0\2\3\10\0\3\3\1\122"+
    "\7\3\1\123\15\3\13\0\6\3\44\0\1\124\64\0"+
    "\1\47\64\0\1\47\1\0\1\46\70\0\1\41\16\0"+
    "\1\125\61\0\2\3\10\0\31\3\13\0\1\3\1\126"+
    "\4\3\7\52\1\127\1\130\54\52\7\131\1\132\1\131"+
    "\1\52\53\131\1\0\2\3\10\0\2\3\1\133\26\3"+
    "\13\0\6\3\1\0\2\3\10\0\2\3\1\134\26\3"+
    "\13\0\6\3\1\0\2\3\10\0\6\3\1\135\22\3"+
    "\13\0\6\3\1\0\2\3\10\0\7\3\1\136\21\3"+
    "\13\0\6\3\1\0\2\3\10\0\3\3\1\137\25\3"+
    "\13\0\6\3\1\0\2\3\10\0\1\140\3\3\1\141"+
    "\24\3\13\0\6\3\1\0\2\3\10\0\11\3\1\142"+
    "\17\3\13\0\6\3\1\0\2\3\10\0\7\3\1\143"+
    "\21\3\13\0\6\3\1\0\2\3\10\0\23\3\1\144"+
    "\5\3\13\0\6\3\1\0\2\3\10\0\15\3\1\145"+
    "\13\3\13\0\6\3\1\0\2\3\10\0\1\146\12\3"+
    "\1\106\15\3\13\0\6\3\1\0\2\3\10\0\4\3"+
    "\1\147\10\3\1\150\13\3\13\0\6\3\1\0\2\3"+
    "\10\0\3\3\1\151\25\3\13\0\6\3\1\0\2\3"+
    "\10\0\2\3\1\137\1\152\25\3\13\0\6\3\1\0"+
    "\2\3\10\0\11\3\1\153\17\3\13\0\6\3\1\0"+
    "\2\3\10\0\1\154\30\3\13\0\6\3\1\0\2\3"+
    "\10\0\1\112\30\3\13\0\6\3\1\0\2\3\10\0"+
    "\2\3\1\137\26\3\13\0\6\3\1\0\2\3\10\0"+
    "\16\3\1\155\12\3\13\0\6\3\1\0\2\3\10\0"+
    "\3\3\1\156\25\3\13\0\6\3\1\0\2\3\10\0"+
    "\11\3\1\157\17\3\13\0\6\3\1\0\2\3\10\0"+
    "\3\3\1\160\25\3\13\0\6\3\1\0\2\3\10\0"+
    "\26\3\1\106\2\3\13\0\6\3\1\0\2\3\10\0"+
    "\2\3\1\161\1\162\25\3\13\0\6\3\1\0\2\3"+
    "\10\0\23\3\1\163\5\3\13\0\6\3\1\0\2\3"+
    "\10\0\20\3\1\164\10\3\13\0\6\3\1\0\2\3"+
    "\10\0\16\3\1\165\12\3\13\0\6\3\1\0\2\3"+
    "\10\0\4\3\1\106\24\3\13\0\6\3\1\0\2\3"+
    "\10\0\7\3\1\166\21\3\13\0\6\3\1\0\2\3"+
    "\10\0\11\3\1\167\17\3\13\0\6\3\1\0\2\3"+
    "\10\0\5\3\1\170\23\3\13\0\6\3\1\0\2\3"+
    "\10\0\7\3\1\171\5\3\1\172\13\3\13\0\6\3"+
    "\1\0\2\3\10\0\1\3\1\173\27\3\13\0\6\3"+
    "\1\0\2\3\10\0\10\3\1\174\4\3\1\175\13\3"+
    "\13\0\6\3\1\0\2\3\10\0\15\3\1\176\13\3"+
    "\13\0\6\3\1\0\2\3\10\0\4\3\1\177\24\3"+
    "\13\0\6\3\1\0\2\3\10\0\2\3\1\200\26\3"+
    "\13\0\6\3\2\0\1\201\63\0\2\3\10\0\31\3"+
    "\13\0\2\3\1\202\3\3\11\132\1\0\53\132\1\0"+
    "\2\3\10\0\3\3\1\203\25\3\13\0\6\3\1\0"+
    "\2\3\10\0\6\3\1\143\22\3\13\0\6\3\1\0"+
    "\2\3\10\0\1\204\30\3\13\0\6\3\1\0\2\3"+
    "\10\0\10\3\1\205\20\3\13\0\6\3\1\0\2\3"+
    "\10\0\6\3\1\106\22\3\13\0\6\3\1\0\2\3"+
    "\10\0\3\3\1\206\25\3\13\0\6\3\1\0\2\3"+
    "\10\0\15\3\1\207\13\3\13\0\6\3\1\0\2\3"+
    "\10\0\5\3\1\210\23\3\13\0\6\3\1\0\2\3"+
    "\10\0\4\3\1\211\24\3\13\0\6\3\1\0\2\3"+
    "\10\0\6\3\1\112\22\3\13\0\6\3\1\0\2\3"+
    "\10\0\3\3\1\152\25\3\13\0\6\3\1\0\2\3"+
    "\10\0\11\3\1\212\17\3\13\0\6\3\1\0\2\3"+
    "\10\0\7\3\1\213\21\3\13\0\6\3\1\0\2\3"+
    "\10\0\2\3\1\106\26\3\13\0\6\3\1\0\2\3"+
    "\10\0\16\3\1\214\12\3\13\0\6\3\1\0\2\3"+
    "\10\0\5\3\1\215\23\3\13\0\6\3\1\0\2\3"+
    "\10\0\3\3\1\216\25\3\13\0\6\3\1\0\2\3"+
    "\10\0\2\3\1\150\26\3\13\0\6\3\1\0\2\3"+
    "\10\0\21\3\1\106\7\3\13\0\6\3\1\0\2\3"+
    "\10\0\6\3\1\217\22\3\13\0\6\3\1\0\2\3"+
    "\10\0\24\3\1\106\4\3\13\0\6\3\1\0\2\3"+
    "\10\0\15\3\1\220\13\3\13\0\6\3\1\0\2\3"+
    "\10\0\3\3\1\221\25\3\13\0\6\3\1\0\2\3"+
    "\10\0\6\3\1\222\22\3\13\0\6\3\1\0\2\3"+
    "\10\0\7\3\1\143\1\223\20\3\13\0\6\3\1\0"+
    "\2\3\10\0\1\224\30\3\13\0\6\3\1\0\2\3"+
    "\10\0\1\3\1\176\27\3\13\0\6\3\1\0\2\3"+
    "\10\0\1\211\30\3\13\0\6\3\1\0\2\3\10\0"+
    "\1\225\30\3\13\0\6\3\1\0\2\3\10\0\12\3"+
    "\1\226\16\3\13\0\6\3\1\0\2\3\10\0\3\3"+
    "\1\227\25\3\13\0\6\3\1\0\2\3\10\0\11\3"+
    "\1\230\13\3\1\231\3\3\13\0\6\3\1\0\2\3"+
    "\10\0\10\3\1\206\20\3\13\0\6\3\1\0\2\3"+
    "\10\0\1\232\30\3\13\0\6\3\1\0\2\3\10\0"+
    "\17\3\1\106\11\3\13\0\6\3\1\0\2\3\10\0"+
    "\10\3\1\137\20\3\13\0\6\3\1\0\2\3\10\0"+
    "\15\3\1\102\13\3\13\0\6\3\1\0\2\3\10\0"+
    "\3\3\1\233\25\3\13\0\6\3\2\0\1\201\53\0"+
    "\1\234\7\0\2\3\10\0\31\3\13\0\3\3\1\235"+
    "\2\3\1\0\2\3\10\0\4\3\1\236\24\3\13\0"+
    "\6\3\1\0\2\3\10\0\12\3\1\106\16\3\13\0"+
    "\6\3\1\0\2\3\10\0\6\3\1\237\22\3\13\0"+
    "\6\3\1\0\2\3\10\0\15\3\1\240\13\3\13\0"+
    "\6\3\1\0\2\3\10\0\5\3\1\241\23\3\13\0"+
    "\6\3\1\0\2\3\10\0\14\3\1\242\14\3\13\0"+
    "\6\3\1\0\2\3\10\0\3\3\1\106\25\3\13\0"+
    "\6\3\1\0\2\3\10\0\2\3\1\243\26\3\13\0"+
    "\6\3\1\0\2\3\10\0\26\3\1\244\2\3\13\0"+
    "\6\3\1\0\2\3\10\0\4\3\1\245\24\3\13\0"+
    "\6\3\1\0\2\3\10\0\14\3\1\106\14\3\13\0"+
    "\6\3\1\0\2\3\10\0\15\3\1\246\13\3\13\0"+
    "\6\3\1\0\2\3\10\0\11\3\1\247\17\3\13\0"+
    "\6\3\1\0\2\3\10\0\25\3\1\137\3\3\13\0"+
    "\6\3\1\0\2\3\10\0\1\250\30\3\13\0\6\3"+
    "\1\0\2\3\10\0\4\3\1\251\24\3\13\0\6\3"+
    "\1\0\2\3\10\0\6\3\1\252\22\3\13\0\6\3"+
    "\1\0\2\3\10\0\16\3\1\253\12\3\13\0\6\3"+
    "\1\0\2\3\10\0\10\3\1\254\20\3\13\0\6\3"+
    "\1\0\2\3\10\0\1\255\30\3\13\0\6\3\1\0"+
    "\2\3\10\0\6\3\1\256\22\3\13\0\6\3\1\0"+
    "\2\3\10\0\3\3\1\257\25\3\13\0\6\3\1\0"+
    "\2\3\10\0\1\62\30\3\13\0\6\3\1\0\2\3"+
    "\10\0\3\3\1\121\25\3\13\0\6\3\1\0\2\3"+
    "\10\0\6\3\1\260\22\3\13\0\6\3\1\0\2\3"+
    "\7\0\1\261\31\3\13\0\6\3\1\0\2\3\10\0"+
    "\1\262\30\3\13\0\6\3\1\0\2\3\10\0\1\245"+
    "\30\3\13\0\6\3\1\0\2\3\10\0\5\3\1\106"+
    "\23\3\13\0\6\3\1\0\2\3\10\0\3\3\1\263"+
    "\25\3\13\0\6\3\1\0\2\3\10\0\4\3\1\264"+
    "\24\3\13\0\6\3\1\0\2\3\10\0\15\3\1\265"+
    "\13\3\13\0\6\3\1\0\2\3\10\0\11\3\1\106"+
    "\17\3\13\0\6\3\1\0\2\3\10\0\11\3\1\266"+
    "\17\3\13\0\6\3\1\0\2\3\10\0\17\3\1\150"+
    "\11\3\13\0\6\3\1\0\2\3\10\0\11\3\1\267"+
    "\17\3\13\0\6\3\1\0\2\3\10\0\20\3\1\270"+
    "\10\3\13\0\6\3\1\0\2\3\10\0\21\3\1\271"+
    "\7\3\13\0\6\3\1\0\2\3\10\0\10\3\1\211"+
    "\20\3\13\0\6\3\1\0\2\3\10\0\10\3\1\272"+
    "\20\3\13\0\6\3\1\0\2\3\10\0\24\3\1\137"+
    "\4\3\13\0\6\3\1\0\2\3\10\0\5\3\1\273"+
    "\23\3\13\0\6\3\1\0\2\3\10\0\10\3\1\245"+
    "\20\3\13\0\6\3\1\0\2\3\10\0\21\3\1\274"+
    "\7\3\13\0\6\3\63\0\1\275\2\0\2\3\10\0"+
    "\5\3\1\211\23\3\13\0\6\3\1\0\2\3\10\0"+
    "\20\3\1\276\10\3\13\0\6\3\1\0\2\3\10\0"+
    "\7\3\1\277\21\3\13\0\6\3\1\0\2\3\10\0"+
    "\6\3\1\300\22\3\13\0\6\3\1\0\2\3\10\0"+
    "\16\3\1\137\12\3\13\0\6\3\1\0\2\3\10\0"+
    "\5\3\1\301\23\3\13\0\6\3\1\0\2\3\10\0"+
    "\1\302\30\3\13\0\6\3\1\0\2\3\10\0\6\3"+
    "\1\303\22\3\13\0\6\3\1\0\2\3\10\0\13\3"+
    "\1\106\15\3\13\0\6\3\1\0\2\3\10\0\3\3"+
    "\1\304\25\3\13\0\6\3\1\0\2\3\7\0\1\305"+
    "\31\3\13\0\6\3\30\0\1\306\35\0\2\3\10\0"+
    "\23\3\1\106\5\3\13\0\6\3\1\0\2\3\10\0"+
    "\11\3\1\307\17\3\13\0\6\3\1\0\2\3\10\0"+
    "\11\3\1\211\17\3\13\0\6\3\1\0\2\3\10\0"+
    "\6\3\1\310\22\3\13\0\6\3\1\0\2\3\10\0"+
    "\5\3\1\137\23\3\13\0\6\3\1\0\2\3\10\0"+
    "\11\3\1\311\17\3\13\0\6\3\1\0\2\3\10\0"+
    "\6\3\1\175\22\3\13\0\6\3\22\0\1\312\66\0"+
    "\1\313\41\0\2\3\10\0\15\3\1\314\13\3\13\0"+
    "\6\3\1\0\2\3\10\0\7\3\1\315\21\3\13\0"+
    "\6\3\1\0\2\3\10\0\3\3\1\150\25\3\13\0"+
    "\6\3\31\0\1\316\117\0\1\317\1\0\2\3\10\0"+
    "\30\3\1\304\13\0\6\3\1\0\2\3\10\0\20\3"+
    "\1\106\10\3\13\0\6\3\16\0\1\320\70\0\1\321"+
    "\54\0\1\127\71\0\1\322\101\0\1\320\30\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10176];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\10\1\1\11\25\1\1\11\4\1\2\11"+
    "\1\0\1\11\1\0\51\1\1\11\1\0\1\1\1\11"+
    "\51\1\1\0\32\1\1\11\24\1\1\0\13\1\1\0"+
    "\7\1\2\0\3\1\2\0\2\1\5\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 164) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 12: 
          { lexeme=yytext(); return PALRE;
          }
        case 13: break;
        case 8: 
          { lexeme=yytext(); return OPLOG;
          }
        case 14: break;
        case 7: 
          { lexeme=yytext(); return OPASI;
          }
        case 15: break;
        case 2: 
          { lexeme=yytext(); return ID;
          }
        case 16: break;
        case 11: 
          { lexeme=yytext(); return CDNA;
          }
        case 17: break;
        case 1: 
          { return ERROR;
          }
        case 18: break;
        case 3: 
          { lexeme=yytext(); return NUM;
          }
        case 19: break;
        case 9: 
          { lexeme=yytext(); return OPREL;
          }
        case 20: break;
        case 6: 
          { lexeme=yytext(); return OPESP;
          }
        case 21: break;
        case 10: 
          { lexeme=yytext(); return OPIND;
          }
        case 22: break;
        case 5: 
          { /*Ignore*/
          }
        case 23: break;
        case 4: 
          { lexeme=yytext(); return OPARI;
          }
        case 24: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
